# Data Programming in Python | BAIS:6040
# Notebook Demonstration 5.5 - Array Operations, Functions, and Methods

## Array Operations

NumPy arrays allows you to express batch operations on data without writing any <b>for</b> loops. This is usually called vectorization. Any arithmetic operations between equal-size arrays applies the operation elementwise.

In [1]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [5]:
x + 1                   # a new numpy array with each value in x added by 1

array([2, 3, 4, 5, 6])

This is called element-wise addition.

In [6]:
l = [1, 2, 3, 4, 5]
l + 1

TypeError: can only concatenate list (not "int") to list

Note that primitive Python lists do not support this element-wise operation.

In [ ]:
[num + 1 for num in l]

You need a <b>for</b> loop or list comprehension to do the same thing with a primitive Python list.

In [7]:
x

array([1, 2, 3, 4, 5])

In [8]:
x - 1

array([0, 1, 2, 3, 4])

In [9]:
x * 2

array([ 2,  4,  6,  8, 10])

In [10]:
x / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [11]:
-x

array([-1, -2, -3, -4, -5])

In [12]:
1 / x

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [13]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [14]:
x = np.array([1, 2, 3])
y = np.array([1, 3, 5])


In [ ]:
x1 = [1, 2, 3]
y1 = [1, 3, 5]

x1 + y1

Note that list1 + list2 performs concatenation, not element-wise addition

In [15]:
x + y

array([2, 5, 8])

In [16]:
x * y

array([ 1,  6, 15])

In [17]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 3, 5])
x + y

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

For element-wise array operations, the two operands must have the same shape for addition, subtraction, muliplication, and division. 

## Fast Element-wise Array Functions

Mathematical functions: https://numpy.org/doc/stable/reference/routines.math.html

In [ ]:
x = np.array([-1, 2, -3, 4, -5])
np.absolute(x)      # absolute values

In [ ]:
abs(x)

numpy.absolute: https://numpy.org/doc/stable/reference/generated/numpy.absolute.html

In [ ]:
x = np.array([1, 2, 3])
np.exp(x)            # exponential (= e^x)

numpy.exp: https://numpy.org/doc/stable/reference/generated/numpy.exp.html

In [ ]:
x = np.array([1, 2, 3])
np.power(3, x)        # power (= 3^x)

In [ ]:
np.power(x, 3)        # power (= x^3), is equivalent to x**3

In [ ]:
x ** 3

numpy.power: https://numpy.org/doc/stable/reference/generated/numpy.power.html

## Array Methods

In [ ]:
np.random.seed(0)
x = np.random.randint(1, 50, 10)
x

In [18]:
x.sum()

np.int64(15)

numpy.ndarray.sum: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html

In [ ]:
x.prod()

numpy.ndarray.prod: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.prod.html

In [19]:
x.mean()           # Returns the mean of the array elements

np.float64(3.0)

numpy.ndarray.mean: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.mean.html

In [ ]:
x.var()           # Returns the variance of the array elements.

numpy.ndarray.var: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.var.html

In [ ]:
x.std()           # Returns the standard deviation of the array elements

numpy.ndarray.std: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.std.html

In [ ]:
x.min()           # Return the minimum along a given axis

numpy.ndarray.min: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html

In [ ]:
x.max()           # Return the maximum along a given axis

numpy.ndarray.max: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html

In [ ]:
x.argmin()

numpy.ndarray.argmin: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argmin.html

The <b>argmin</b>(axis=None, out=None) returns indices of the minimum values along the given `axis` of a.

In [ ]:
x.argmax()

numpy.ndarray.argmax: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argmax.html

The <b>argmax</b>(axis=None, out=None) returns indices of the maximum values along the given `axis`.

In [20]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
y = x.reshape((3, 5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

numpy.ndarray.reshape: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html

The <b>reshape</b>(shape, ...) method returns an array containing the same data with a new `shape`.

In [22]:
y.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

numpy.ndarray.transpose: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html

The <b>transpose</b>(*axes) returns a view of the array with `axes` transposed.

In [ ]:
y.T

In [23]:
y1 = y.flatten()

numpy.ndarray.flatten: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html

The <b>flatten</b> method returns a copy of the array collapsed into one dimension. The <b>flatten</b> function is the opposite of <b>reshape</b>.

In [24]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.asarray(x1)   # change of y1 will also affect x1

In [25]:
y1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y1.fill(0)

In [ ]:
x1

In [ ]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = x2.copy()   # change of y2 will NOT affect x2

numpy.ndarray.copy: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy 

The <b>copy</b> method returns a copy of the array.

In [ ]:
y2

In [ ]:
y2.fill(0)

numpy.ndarray.fill: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.fill.html

The <b>fill</b> method fill the array with a scalar value. Fill expects a scalar value and always behaves the same as assigning to a single array element.

In [ ]:
y2

In [ ]:
x2

In [ ]:
x.dtype

In [ ]:
x.astype(float)

numpy.ndarray.astype: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

The <b>astype</b>(dtype, ...) method casts an array to a specified `dtype`.