# Data Programming in Python | BAIS:6040
# Notebook Demonstration 5.4 - Array Indexing and Slicing

## Array Indexing & Slicing

Indexing and slicing of NumPy arrays works basically the same as general indexing and slicing in Python, with some additional functionality such as Boolean indexing and Fancy Indexing. 

In [47]:
import numpy as np

### 1-dimensional Arrays

In [48]:
np.random.seed(0)
x = np.random.randint(10, 100, 10)
x

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 97], dtype=int32)

In [49]:
x[0]                          # get the first number in x

np.int32(54)

In [50]:
x[-1]                         # get the last number in x

np.int32(97)

In [5]:
x[:3]                          # get the first three numbers in x

array([54, 57, 74], dtype=int32)

In [6]:
x[-3:]                          # get the last three numbers in x

array([31, 46, 97], dtype=int32)

In [7]:
x[:]

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 97], dtype=int32)

`x[:]` is equivalent to just `x`. 

In [8]:
x[::2]

array([54, 74, 77, 93, 46], dtype=int32)

In [9]:
x[::-1] 

array([97, 46, 31, 93, 19, 77, 77, 74, 57, 54], dtype=int32)

`x[::-1]` reverses `x`.

### 2-dimensional Arrays

# array_name[rows, columns]

In [51]:
np.random.seed(0)
x = np.random.randint(0, 100, (5, 10))
x

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72,  9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74, 23, 35]], dtype=int32)

You can think of a 2-dimensional array as a matrix with rows and columns. 

In [11]:
x[0]        # Selects the first row from the matrix

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87], dtype=int32)

In [12]:
x[:3]       # The first 3 rows

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72,  9, 20, 80, 69, 79]], dtype=int32)

`x[:n]` retrieves the first `n` rows.

In [13]:
x[0, 1]      # The first row and the second column 

np.int32(47)

In [14]:
x[0][1]      # equals to x[0,1] but is LESS efficient as a new temporary array is created after the first index.

np.int32(47)

When retrieving a particular value in a 2-dimensional array, look up the row index first and then the column index, separated by a comma in matching square brackets.

In [15]:
list_x = [[1,2,3],[4,5,6],[7,8,9]]      # x1 is a list of lists

In [16]:
list_x[0][1]                            # the only indexing method for list

2

In [17]:
list_x[1, 2]                            # wrong

TypeError: list indices must be integers or slices, not tuple

In [18]:
x[:3, :3]    # The first 3 rows and the first 3 columns

array([[44, 47, 64],
       [70, 88, 88],
       [81, 37, 25]], dtype=int32)

In [19]:
x[-3:, -3:] # The last 3 rows and the last 3 columns

array([[80, 69, 79],
       [19, 19, 14],
       [74, 23, 35]], dtype=int32)

In [20]:
x[:3, -5:] # The first 3 rows and the last 5 columns 

array([[ 9, 83, 21, 36, 87],
       [65, 39, 87, 46, 88],
       [ 9, 20, 80, 69, 79]], dtype=int32)

In [21]:
x[:, :3]    # All rows and the first 3 columns

array([[44, 47, 64],
       [70, 88, 88],
       [81, 37, 25],
       [47, 64, 82],
       [39, 32, 65]], dtype=int32)

`x[:, :n]` retrieves the first `n` columns.

<hr>

### Boolean indexing

In [22]:
import numpy as np

In [23]:
np.random.seed(0)
data = np.random.normal(75, 10, (7, 3))
data

array([[92.64052346, 79.00157208, 84.78737984],
       [97.40893199, 93.6755799 , 65.2272212 ],
       [84.50088418, 73.48642792, 73.96781148],
       [79.10598502, 76.44043571, 89.54273507],
       [82.61037725, 76.21675016, 79.43863233],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

In [24]:
data > 90

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [25]:
b_mask = data > 90

In [26]:
data[b_mask]

array([92.64052346, 97.40893199, 93.6755799 ])

In [27]:
data[data > 90]     # Returns all the values in data that are greater than 90.

array([92.64052346, 97.40893199, 93.6755799 ])

This Boolean array can be passed as a mask when indexing the array. This is called Boolean indexing. The Boolean array must be of the same length as the axis it is indexing. Boolean indexing returns an array of the values that correspond to True. 

In [28]:
names = np.array(['Bob', 'Alice', 'Sam', 'Bob', 'Sam', 'Alice', 'Alice'])
names

array(['Bob', 'Alice', 'Sam', 'Bob', 'Sam', 'Alice', 'Alice'], dtype='<U5')

Suppose each name in `names` corresponds to a row in `data`.

In [29]:
data

array([[92.64052346, 79.00157208, 84.78737984],
       [97.40893199, 93.6755799 , 65.2272212 ],
       [84.50088418, 73.48642792, 73.96781148],
       [79.10598502, 76.44043571, 89.54273507],
       [82.61037725, 76.21675016, 79.43863233],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

In [30]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

Comparing `names` with a string *Bob* yields a Boolean array of element-wise answers.

In [31]:
data[names == "Bob"]    # Returns all the values in data that correspond to Bob.

array([[92.64052346, 79.00157208, 84.78737984],
       [79.10598502, 76.44043571, 89.54273507]])

In [32]:
data[[True, False, False,  True, False, False, False]]

array([[92.64052346, 79.00157208, 84.78737984],
       [79.10598502, 76.44043571, 89.54273507]])

This Boolean array can be passed as a mask when indexing the `data` array.

In [33]:
data[names == "Alice"]   # Returns all the values in data that correspond to Alice.

array([[97.40893199, 93.6755799 , 65.2272212 ],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

In [34]:
data[(data[:,1]>80) & (names == 'Alice')]

array([[97.40893199, 93.6755799 , 65.2272212 ],
       [78.33674327, 89.94079073, 72.94841736]])

To make a compound condition, use Boolean arithmetic operators such as & (i.e., and) and | (i.e., or). 

In [35]:
mask = (names == 'Bob') | (names == 'Alice')
data[mask]

array([[92.64052346, 79.00157208, 84.78737984],
       [97.40893199, 93.6755799 , 65.2272212 ],
       [79.10598502, 76.44043571, 89.54273507],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

If the condition is too long and complex, you can assign the resulting Boolean array to a variable, say `mask`, and then you can pass the `mask` for indexing `data`.

Note that selecting data from an array by Boolean indexing always returns a copy of the target array, not changing its content.

In [36]:
data < 80

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [37]:
data[data < 80]

array([79.00157208, 65.2272212 , 73.48642792, 73.96781148, 79.10598502,
       76.44043571, 76.21675016, 79.43863233, 78.33674327, 72.94841736,
       78.13067702, 66.45904261, 49.47010184])

In [38]:
data[data < 80] = 0     # Sets all of the values less than 80 to 0.
data


array([[92.64052346,  0.        , 84.78737984],
       [97.40893199, 93.6755799 ,  0.        ],
       [84.50088418,  0.        ,  0.        ],
       [ 0.        ,  0.        , 89.54273507],
       [82.61037725,  0.        ,  0.        ],
       [ 0.        , 89.94079073,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [39]:
data[data==0] = data.mean()

In [40]:
data

array([[92.64052346, 34.05272392, 84.78737984],
       [97.40893199, 93.6755799 , 34.05272392],
       [84.50088418, 34.05272392, 34.05272392],
       [34.05272392, 34.05272392, 89.54273507],
       [82.61037725, 34.05272392, 34.05272392],
       [34.05272392, 89.94079073, 34.05272392],
       [34.05272392, 34.05272392, 34.05272392]])

You can set values with boolean arrays. Only the values that correspond to True are affected. 

In [41]:
data[names == "Sam"]

array([[84.50088418, 34.05272392, 34.05272392],
       [82.61037725, 34.05272392, 34.05272392]])

In [42]:
data[names == "Sam"] = 999
data

array([[ 92.64052346,  34.05272392,  84.78737984],
       [ 97.40893199,  93.6755799 ,  34.05272392],
       [999.        , 999.        , 999.        ],
       [ 34.05272392,  34.05272392,  89.54273507],
       [999.        , 999.        , 999.        ],
       [ 34.05272392,  89.94079073,  34.05272392],
       [ 34.05272392,  34.05272392,  34.05272392]])

In [43]:
data[names == "Sam"] = [100, 99, 98]
data

array([[ 92.64052346,  34.05272392,  84.78737984],
       [ 97.40893199,  93.6755799 ,  34.05272392],
       [100.        ,  99.        ,  98.        ],
       [ 34.05272392,  34.05272392,  89.54273507],
       [100.        ,  99.        ,  98.        ],
       [ 34.05272392,  89.94079073,  34.05272392],
       [ 34.05272392,  34.05272392,  34.05272392]])

This way, you can set the whole rows or columns.

### Fancy Indexing

Fancy Indexing is a term coined by NumPy to describe indexing using integer arrays.

In [44]:
x = np.array([num * 10 for num in np.arange(10)])
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
mask = [0, 7, 1]
x[mask]

array([ 0, 70, 10])

To select a subset of the values in a particular order, you can simply pass a list or array of index positions, specifying the desired order.

In [46]:
mask = [-1, -5, -3]
x[mask]

array([90, 50, 70])

You can always use negative index positions. 