# Data Programming in Python | BAIS:6040
# Notebook Demonstration 4.5 - Pandas Series

## Data Structures in Pandas

Pandas provides two types of classes for handling data:
- Series
- DataFrame

In [1]:
from IPython.display import Image

Image(url="https://cdn-images-1.medium.com/max/800/0*PWbW0OdJJw49kxMt.png")

Series are one-dimensional arrays. A series has values (e.g., X0 to X3) along with an index of positions or labels (e.g., A, B, C, and D). The index is used to access the values in the series. 

In [2]:
Image(url="https://cdn-images-1.medium.com/max/800/0*dddYH8GijZanG4dO.png")

Dataframes are two-dimensional data structures. A dataframe is designed to extend series to two dimensions. A dataframe has values (e.g., A0 to D3) along with two indices for accessing the values: a row index called just index (e.g., 0, 1, 2, and 3) and a column index called columns (e.g., A, B, C, and D). A dataframe is, in fact, a collection of mulitple series, each of which shares an index. 

## Importing the Pandas Package

In [3]:
#! pip install --user --upgrade pandas

In [4]:
import pandas as pd
import numpy as np

C:\Users\redmo\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


## Pandas Series

In [5]:
data = list(range(10, 101, 10))
data

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [6]:
series = pd.Series(data=data)     # Create a Pandas series from a list. 
series

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

pandas.Series: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

The right-hand side is the values of the `series`, and the left-hand side is the index of the `series`. If you do not specify any index during the series creation, Pandas will, by default, assign integer values increasing from 0 by 1 as its index.

In [7]:
type(series)

pandas.core.series.Series

In [8]:
series.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
list(series.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
series.values

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int64)

In [11]:
s = pd.Series(data=np.arange(10, 51, 10), index = ["a", "b", "c", "d", "e"]) 
s

a    10
b    20
c    30
d    40
e    50
dtype: int32

If data is an ndarray, index must be the same length as data. If no index is passed, one will be created having values [0, ..., len(data) - 1]

In [12]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [13]:
s.values

array([10, 20, 30, 40, 50])

## Selecting Elements from a Series

Element selection from a series is the same as that from any other iterable object in Python. 

In [14]:
series

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [15]:
series[0]

10

In [16]:
series[:3]

0    10
1    20
2    30
dtype: int64

In [17]:
series[-3:]

7     80
8     90
9    100
dtype: int64

In [18]:
for num in series:
    print(num)

10
20
30
40
50
60
70
80
90
100


When iterating over a series, only the values are exposed. The index is not exposed, which means the index is only used for accessing elements in a series. 

In [19]:
index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]     
series2 = pd.Series(data=data, index=index)                  # Use Alphabet letters as the index of a series.
series2

a     10
b     20
c     30
d     40
e     50
f     60
g     70
h     80
i     90
j    100
dtype: int64

Often it is preferable to create a series using meaningful labels, instead of numbers, in order to distinguish and identify each item regardless of the order in which they were inserted into the series. 

In [20]:
series2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [21]:
series2.values

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int64)

In [22]:
series2["a"]

10

You can select individual elements, specifying the label corresponding to the position of the index. 

In [23]:
series2.a

10

`series.a` is equivalent to `series["a"]` if `a` is a string.

In [24]:
series2[0]

C:\Users\redmo\AppData\Local\Temp\ipykernel_31364\652758247.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series2[0]


10

Element selection specifying the index position still works. 

In [25]:
series2[:3]

a    10
b    20
c    30
dtype: int64

In [26]:
series2[["a", "c", "b"]]

a    10
c    30
b    20
dtype: int64

Fancy indexing still works for Pandas series and dataframes.

In [27]:
for num in series2:
    print(num)

10
20
30
40
50
60
70
80
90
100


In [28]:
index = ["a", "b", "c", "d", "e", "a", "b", "c", "d", "e"]
series3 = pd.Series(data=data, index=index)
series3

a     10
b     20
c     30
d     40
e     50
a     60
b     70
c     80
d     90
e    100
dtype: int64

The index positions and labels do not have to be unique. 

In [29]:
series3[["a", "c", "e"]]

a     10
a     60
c     30
c     80
e     50
e    100
dtype: int64